### PR TITLE
OpenCongress::Person#parse_results needs to parse Array results

### PR DESCRIPTION
**Pull request by jeff-r**
OpenCongress.org returns an Array, rather than a Hash, for a "Senators most in the news" query. 

Person#parse_results assumed it would get a hash; this update lets it check for either.

### CODE REVIEW

**Comment by NateBarnes** [comment]
This appears to be a remnant of the error introduced last weekend. All Person and Bill objects should be receiving a hash { people => [] } rather than an array of hashes per Carl. Thus this should probably  be fixed in the OC API (making it give out hashes consistently) rather than here.

Thanks!

**Comment by NateBarnes** [comment]
For reference the issue where we saw this first was issue #8.

Sorry for any inconvenience.

**Comment by jeff-r** [comment]
Thanks for catching this! 

I missed that comment on issue #8. It should definitely be fixed in OC rather than here.

**Comment by NateBarnes** [comment]
np, obviously I made the mistake too :)

**Pull request closed without merging**
